### PR TITLE
Python tests fixes after merge.

### PR DESCRIPTION
**Pull request by i-Alex**
1) `ws_messages.py` works fine for me
2) `sc_proof_verifier_low_priority_threads.py` fixed
3) `getblockmerkleroots.py`  ignored (was done by cronic in other branch)
4) `sc_block_partitions.py` fixed
5) `sc_csw_eviction_from_mempool.py` fixed.
6) `sc_stale_ft_and_mbtr.py`  interfaces fixed, but seems a bug in the test flow. @alsala please take a look.

### CODE REVIEW

**Review by DanieleDiBenedetto — APPROVED** [review]

**Review by DanieleDiBenedetto — APPROVED** [review]
As I've already said, let's check if getblockmerkleroots.py was failing in my branch due to auto-merge or something or if it's a real bug

**Comment by cronicc** [comment]
CI run with this PR and #148 combined https://app.travis-ci.com/github/HorizenOfficial/zend_oo/builds/237104676

**Comment by cronicc** [comment]
@i-Alex @DanieleDiBenedetto getblockmerkleroots.py passes, but got a couple of other failures.

List of errors in CI, generally timing issues are worse on CI as performance can be unpredictable:

1. `ws_messages.py`
https://app.travis-ci.com/github/HorizenOfficial/zend_oo/jobs/535975332#L1965 and https://app.travis-ci.com/github/HorizenOfficial/zend_oo/jobs/535975338#L1967-L1989
```
Assertion failed: Websocket performs too slow: 1.23874497414 sec. Expect to take less than 1 sec.
Stopping nodes
############ Server closed connection
##### ws client closing
Cleaning up
Failed
!!! FAIL: ws_messages.py !!!
```

6. `sc_stale_ft_and_mbtr.py `
https://app.travis-ci.com/github/HorizenOfficial/zend_oo/jobs/535975333#L840-L886 and https://app.travis-ci.com/github/HorizenOfficial/zend_oo/jobs/535975339#L865-L873
```
=== Running testscript sc_stale_ft_and_mbtr.py ===
  File "/mnt/build/qa/rpc-tests/test_framework/test_framework.py", line 125, in main
    self.run_test()
  File "/mnt/build/qa/rpc-tests/sc_stale_ft_and_mbtr.py", line 334, in run_test
    assert_false(txFT in bl_json['tx'])
  File "/mnt/build/qa/rpc-tests/test_framework/util.py", line 439, in assert_false
    assert_true(not condition, message)
  File "/mnt/build/qa/rpc-tests/test_framework/util.py", line 436, in assert_true
    raise AssertionError(message)
```

new  `sc_cert_getblocktemplate.py`
https://app.travis-ci.com/github/HorizenOfficial/zend_oo/jobs/535975333#L888-L918
```
=== Running testscript sc_cert_getblocktemplate.py ===
______ travis keep alive ______
  File "/mnt/build/qa/rpc-tests/test_framework/test_framework.py", line 125, in main
    self.run_test()
  File "/mnt/build/qa/rpc-tests/sc_cert_getblocktemplate.py", line 181, in run_test
    assert(len(self.nodes[i].getblocktemplate()['certificates']) == 0)
```

**Comment by i-Alex** [comment]
"ws_messages.py" and "sc_cert_getblocktemplate.py" tests were optimized for CI.

**Comment by cronicc** [comment]
New CI run with latest commits and #185 https://app.travis-ci.com/github/HorizenOfficial/zend_oo/builds/237185942

**Review by alsala — APPROVED** [review]

**Pull request merged**
